# Generated by Django 3.0.5 on 2020-05-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Case ID')),
                ('next_visit', models.IntegerField(default=0, verbose_name='Days Before Next Visit')),
                ('kvp', models.FloatField(default=0.0, verbose_name='kVp')),
                ('ma', models.FloatField(default=0.0, verbose_name='mA')),
                ('dlp', models.FloatField(default=0.0, verbose_name='DLP')),
                ('diagnostic_quality', models.CharField(choices=[('O', 'Outstanding'), ('G', 'Good'), ('S', 'Satisfactory')], max_length=1)),
                ('see_physician', models.BooleanField(default=False)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='Nodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('state', models.CharField(choices=[('SL', 'Solid'), ('SS', 'Semi Solid'), ('GG', 'Ground Glass')], max_length=2)),
                ('size', models.CharField(choices=[('UC', 'Unchanged'), ('IN', 'Increased'), ('DC', 'Decreased'), ('NW', 'New')], max_length=2)),
                ('notes', models.TextField()),
                ('fig', models.ImageField(upload_to='Uploads/')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('slice_index', models.IntegerField(default=0, verbose_name='Slice Index')),
                ('diameter', models.FloatField(default=0.0)),
                ('probability', models.FloatField(default=0.0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Case')),
            ],
            options={
                'verbose_name': 'Nodule',
                'verbose_name_plural': 'Nodules',
            },
        ),
    ]
