# Generated by Django 3.0.5 on 2020-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodule',
            name='fig',
            field=models.ImageField(upload_to='Uploads/', verbose_name='Nodule Image'),
        ),
    ]
