# Generated by Django 3.0.5 on 2020-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200503_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='patient_id',
            field=models.CharField(default='1.3.6.1.4.1.14519.5.2.1.6279.6001.208737629504245244513001631764', max_length=150),
            preserve_default=False,
        ),
    ]
